variables:
  _BuildConfig: Release

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

trigger:
  - master
  - release/*

pr: '*'

jobs:
  - template: eng/common/templates/jobs/jobs.yml
    parameters:
      jobs:
        - job: Windows
          enablePublishBuildArtifacts: true
          pool: dotnet-external-temp
          steps:
            - script: eng\common\cibuild.cmd
                -configuration $(_BuildConfig)
                -prepareMachine
              name: Build
              condition: succeeded()

        - job: macOS
          enablePublishBuildArtifacts: true
          pool: Hosted macOS
          steps:
            - script: eng/common/cibuild.sh
                --configuration $(_BuildConfig)
                --prepareMachine
              name: Build
              condition: succeeded()

        - job: Linux
          enablePublishBuildArtifacts: true
          pool: Hosted Ubuntu 1604
          container: LinuxContainer
          steps:
            - script: eng/common/cibuild.sh
                --configuration $(_BuildConfig)
                --prepareMachine
              name: Build
              condition: succeeded()
